
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  git
  fzf
  autojump

  zsh-autosuggestions
  zsh-syntax-highlighting
)

# Personnal config
alias rm="rm -i"
alias mv="mv -i"

# Vim
# alias vim='gvim -v'
# alias vim="vimx"
alias nv="nvim"

# Edge
alias edge="microsoft-edge-beta"

# nvm
source /usr/share/nvm/init-nvm.sh

[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
source /usr/share/nvm/nvm.sh
source /usr/share/nvm/bash_completion
source /usr/share/nvm/install-nvm-exec

# open QQMusic
alias qqmusic="/opt/Tencent/QQMusic/qqmusic-1.1.5.AppImage --no-sandbox"
# close QQMusic
alias killqqmusic="killall -9 qqmusic"

# neofetch | lolcat
alias nfl="neofetch --source ~/.config/neofetch/ascii-art-neofetch/communist | lolcat"
alias nfll="neofetch --source ~/.config/neofetch/ascii-art-neofetch/communist -L | lolcat"

# default editor
export EDITOR=emacs

# vterm
vterm_printf() {
    if [ -n "$TMUX" ] && ([ "${TERM%%-*}" = "tmux" ] || [ "${TERM%%-*}" = "screen" ]); then
        # Tell tmux to pass the escape sequences through
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}