
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  git
  fzf
  autojump

  zsh-autosuggestions
  zsh-syntax-highlighting
)

# Personnal config
alias rm="rm -i"
alias mv="mv -i"

# Vim
# alias vim='gvim -v'
alias vim="vimx"
alias nv="nvim"

# Edge

# open QQMusic
alias qqmusic="/opt/Tencent/QQMusic/qqmusic-1.1.5.AppImage --no-sandbox"
# close QQMusic
alias killqqmusic="killall -9 qqmusic"

# neofetch | lolcat
alias nfl="neofetch --source ~/.config/neofetch/ascii-art-neofetch/communist | lolcat"
alias nfll="neofetch --source ~/.config/neofetch/ascii-art-neofetch/communist -L | lolcat"

# default editor
export EDITOR=nvim
